include:
  - project: freedesktop/ci-templates
    ref: 290b79e0e78eab67a83766f4e9691be554fc4afd
    file:
    - templates/ubuntu.yml

stages:
  - container prep
  - build

.common_variables:
  variables:
    FDO_UPSTREAM_REPO: mobile-broadband/libqrtr-glib
    FDO_DISTRIBUTION_VERSION: '18.04'
    FDO_DISTRIBUTION_TAG: '2021-07-22.1'
    FDO_DISTRIBUTION_PACKAGES: ca-certificates git gcc autoconf automake libtool
                               libgirepository1.0-dev libglib2.0-dev autopoint
                               gtk-doc-tools libglib2.0-doc gobject-introspection
                               valac meson ninja-build

build container:
  extends:
  - .fdo.container-build@ubuntu
  - .common_variables
  stage: container prep
  only:
    - master
    - branches
    - merge_requests
    - tags
    - pushes

build-meson-default:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup _debug_build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=true
    - ninja -C _debug_build
    - ninja -C _debug_build install
    - meson setup _release_build --prefix=/usr --buildtype=release -Dwerror=true -Dgtk_doc=false -Dintrospection=true
    - ninja -C _release_build
    - ninja -C _release_build install
