include:
  - project: freedesktop/ci-templates
    ref: 290b79e0e78eab67a83766f4e9691be554fc4afd
    file:
    - templates/ubuntu.yml

stages:
  - container prep
  - build

.common_variables:
  variables:
    FDO_UPSTREAM_REPO: mobile-broadband/libqrtr-glib
    FDO_DISTRIBUTION_VERSION: '20.04'
    FDO_DISTRIBUTION_TAG: '2021-09-11.1'
    FDO_DISTRIBUTION_PACKAGES: ca-certificates git gcc autoconf automake libtool
                               libgirepository1.0-dev libglib2.0-dev autopoint
                               gtk-doc-tools libglib2.0-doc gobject-introspection
                               valac meson ninja-build

build container:
  extends:
  - .fdo.container-build@ubuntu
  - .common_variables
  stage: container prep
  only:
    - main
    - branches
    - merge_requests
    - tags
    - pushes

build-no-introspection:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - main
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --prefix=/usr --buildtype=release -Dwerror=true -Dgtk_doc=false -Dintrospection=false
    - ninja -C build
    - ninja -C build install

build-release:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - main
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --prefix=/usr --buildtype=release -Dwerror=true -Dgtk_doc=true
    - ninja -C build
    - ninja -C build install
    - ninja -C build dist
    - ninja -C build uninstall
